/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package alnayzak;

import java.awt.event.ItemEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author BaRa' DwEiKaT
 */
public class SSessionFrame extends javax.swing.JFrame {

    EntityManagerFactory emf=null;
    EntityManager em=null;
    Query qr=null;
    List<Training>trainings=null;
    Sessions session=null;
    Training training=null;
    
    public SSessionFrame() {
        initComponents();
        emf=Persistence.createEntityManagerFactory("AlNayzakPU");
        em=emf.createEntityManager();
        initialData();
        this.NumberComboBox.addItem("Please select a training first");
        
    }
    public void initialData(){
        qr=em.createNamedQuery("Training.findAll");
        trainings=qr.getResultList();
        this.TrainingComboBox.addItem("select a training");
        for (Training x : trainings){
            this.TrainingComboBox.addItem(x.getTrainingname());
        }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TrainingComboBox = new javax.swing.JComboBox();
        NumberComboBox = new javax.swing.JComboBox();
        SearchSessionButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Session");

        jLabel1.setText("Number");

        jLabel6.setText("Training Name");

        TrainingComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TrainingComboBoxItemStateChanged(evt);
            }
        });

        SearchSessionButton.setText("Search");
        SearchSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSessionButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ResultTextArea.setColumns(20);
        ResultTextArea.setRows(5);
        jScrollPane1.setViewportView(ResultTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TrainingComboBox, 0, 160, Short.MAX_VALUE)
                            .addComponent(NumberComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrainingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSessionButtonActionPerformed
        //try{
        if(this.TrainingComboBox.getSelectedIndex()!=0)
        {
            training=trainings.get(this.TrainingComboBox.getSelectedIndex()-1);
            qr=em.createQuery("select s from Sessions s where s.sessionnumber=:number");
            System.out.println(BigDecimal.valueOf(Long.valueOf(training.getTrainingnumber().toString()+String.format("%d", this.NumberComboBox.getSelectedIndex()+1))));
            qr.setParameter("number",BigDecimal.valueOf(Long.valueOf(training.getTrainingnumber().toString()+String.format("%d", this.NumberComboBox.getSelectedIndex()+1))));
            session = (Sessions) qr.getSingleResult();
            this.ResultTextArea.setText("Training Name: "+session.getTrainingnumber().getTrainingname()+"\n"+
                    "Session Number: "+session.getSessionnumber()+"\n"+
                    "Location: "+session.getLocationname()+"\n"+
                    "Duration: "+session.getDurations());        
            this.ResultTextArea.setEditable(false);
        }  
        else
            JOptionPane.showMessageDialog(null,"Please Insert Data");
           // }
        //catch(Exception ex)
        //{
        //    JOptionPane.showMessageDialog(null, "Check Your Enteries");
        //} 
    }//GEN-LAST:event_SearchSessionButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        this.ResultTextArea.setText("");
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void TrainingComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TrainingComboBoxItemStateChanged
         if ( evt.getStateChange() == ItemEvent.SELECTED ){
            this.NumberComboBox.removeAllItems();
        int selectedLocationIndex=this.TrainingComboBox.getSelectedIndex()-1;
        
        if(selectedLocationIndex>-1){
                for(int i =1 ;i<=trainings.get(selectedLocationIndex).getNumberofsessions().intValue();i++){
                    this.NumberComboBox.addItem(i);
                }
                
                
            }
        else{
            this.NumberComboBox.addItem("Please select a training first");
        }
       }
    }//GEN-LAST:event_TrainingComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JComboBox NumberComboBox;
    private javax.swing.JTextArea ResultTextArea;
    private javax.swing.JButton SearchSessionButton;
    private javax.swing.JComboBox TrainingComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
