/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package alnayzak;

import java.math.BigDecimal;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author BaRa' DwEiKaT
 */
public class SVolunteerFrame extends javax.swing.JFrame {

    EntityManagerFactory emf=null;
    EntityManager em=null;
    Query qr=null;
    People volunteer=null;
    EditVolunteerFrame evf=null;
    
    public SVolunteerFrame() {
        initComponents();
        emf=Persistence.createEntityManagerFactory("AlNayzakPU");
        em=emf.createEntityManager(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LNameTextField = new javax.swing.JTextField();
        MNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FNameTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        SearchVolunteerButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Volunteer");

        jLabel4.setText("Last Name");

        jLabel3.setText("Middle Name");

        jLabel2.setText("First Name");

        jLabel1.setText("ID");

        SearchVolunteerButton.setText("Search");
        SearchVolunteerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchVolunteerButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ResultTextArea.setColumns(20);
        ResultTextArea.setRows(5);
        jScrollPane1.setViewportView(ResultTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(SearchVolunteerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(FNameTextField)
                            .addComponent(MNameTextField)
                            .addComponent(LNameTextField))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchVolunteerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchVolunteerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchVolunteerButtonActionPerformed
        try{
        if(!this.IDTextField.getText().equals(""))
        {
            qr=em.createNamedQuery("People.findByPeopleid");
            qr.setParameter("peopleid",BigDecimal.valueOf(Long.valueOf(this.IDTextField.getText())));
            volunteer = (People) qr.getSingleResult();
            this.ResultTextArea.setText("ID: "+volunteer.getPeopleid()+"\n"+
                    "Name: "+volunteer.getFname()+" "+volunteer.getMinname()+" "+volunteer.getLname()+"\n"+
                    "Socaial Number: "+volunteer.getEmployee().getSocialnumber()+"\n"+
                    "Address: "+volunteer.getAdress()+"\n"+
                    "Email: "+volunteer.getEmail()+"\n"+
                    "Phone Number: "+volunteer.getPhonenumber()+"\n"+
                    "Sex: "+volunteer.getSex()+"\n");
            this.ResultTextArea.setEditable(false);

        }
        else if(!this.FNameTextField.getText().equals("")&&!this.MNameTextField.getText().equals("")&&!this.LNameTextField.getText().equals(""))
        {
            qr=em.createQuery("select p from People p where p.fname=:fname and p.minname=:mname and p.lname=:lname");
            qr.setParameter("fname",this.FNameTextField.getText());
            qr.setParameter("mname",this.MNameTextField.getText());
            qr.setParameter("lname",this.LNameTextField.getText());           
            volunteer = (People) qr.getSingleResult();
            this.ResultTextArea.setText("ID: "+volunteer.getPeopleid()+"\n"+
                    "Name: "+volunteer.getFname()+" "+volunteer.getMinname()+" "+volunteer.getLname()+"\n"+
                    "Socaial Number: "+volunteer.getEmployee().getSocialnumber()+"\n"+
                    "Address: "+volunteer.getAdress()+"\n"+
                    "Email: "+volunteer.getEmail()+"\n"+
                    "Phone Number: "+volunteer.getPhonenumber()+"\n"+
                    "Sex: "+volunteer.getSex()+"\n");
            this.ResultTextArea.setEditable(false);
            
        }
        else
            JOptionPane.showMessageDialog(null,"Please Insert Data");
            }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Check Your Enteries");
        }
    }//GEN-LAST:event_SearchVolunteerButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();
        this.FNameTextField.setText("");
        this.MNameTextField.setText("");
        this.LNameTextField.setText("");
        this.IDTextField.setText("");
        this.ResultTextArea.setText("");
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FNameTextField;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField LNameTextField;
    private javax.swing.JTextField MNameTextField;
    private javax.swing.JTextArea ResultTextArea;
    private javax.swing.JButton SearchVolunteerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
