/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package alnayzak;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author BaRa' DwEiKaT
 */
public class TrainerFrame extends javax.swing.JFrame {
    
    AddSessionFrame asef = null;
    AddTrainingFrame atf  = null;
    AddStudentFrame asf = null;
    SearchTrainingFrame stf  = null;
    SearchStudentFrame ssf = null;
    SSessionFrame Sssef = null;
    STrainingFrame Sstf  = null;
    SStudentFrame Sssf = null;
    SLocationFrame Sslf = null;
    Connection con=null;
    InputStream input=null;
    
    JasperDesign jasperDesign=null;
    JasperReport jasperReport=null;
    JasperPrint jasperPrint=null;
    OutputStream output=null;
    OracleDataSource ods=null;
    ChangeTRPasswordFrame ctrpf = null;
    
    public TrainerFrame() {
        initComponents();
         ctrpf = new ChangeTRPasswordFrame();
         asef= new AddSessionFrame();
         atf=new AddTrainingFrame();
         asf  = new AddStudentFrame();
         stf=new SearchTrainingFrame();
         ssf  = new SearchStudentFrame();
         Sssef= new SSessionFrame();
         Sstf=new STrainingFrame();
         Sssf  = new SStudentFrame();
         Sslf = new SLocationFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        AdministratorMenuBar = new javax.swing.JMenuBar();
        AddMenu = new javax.swing.JMenu();
        AddSessionMenuItem = new javax.swing.JMenuItem();
        AddTrainingMenuItem = new javax.swing.JMenuItem();
        AddStudentMenuItem = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        EditTrainingMenuItem = new javax.swing.JMenuItem();
        EditStudentMenuItem = new javax.swing.JMenuItem();
        SearchMenu = new javax.swing.JMenu();
        SearchLocationMenuItem = new javax.swing.JMenuItem();
        SearchSessionMenuItem = new javax.swing.JMenuItem();
        SearchStudentMenuItem = new javax.swing.JMenuItem();
        SearchTrainingMenuItem = new javax.swing.JMenuItem();
        ReportsMenu = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        SessionsStudentsInformationMenuItem = new javax.swing.JMenuItem();
        SessionsDurationMenuItem = new javax.swing.JMenuItem();
        StudentsInformationMenuItem = new javax.swing.JMenuItem();
        OptionsMenu = new javax.swing.JMenu();
        ChangePasswordMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trainer - Alnayzak");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alnayzak/AlNayzak Logo.jpg"))); // NOI18N

        AdministratorMenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AdministratorMenuBar.setPreferredSize(new java.awt.Dimension(107, 30));

        AddMenu.setText("Add");
        AddMenu.setToolTipText("");

        AddSessionMenuItem.setText("Session");
        AddSessionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSessionMenuItemActionPerformed(evt);
            }
        });
        AddMenu.add(AddSessionMenuItem);

        AddTrainingMenuItem.setText("Training");
        AddTrainingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTrainingMenuItemActionPerformed(evt);
            }
        });
        AddMenu.add(AddTrainingMenuItem);

        AddStudentMenuItem.setText("Student");
        AddStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentMenuItemActionPerformed(evt);
            }
        });
        AddMenu.add(AddStudentMenuItem);

        AdministratorMenuBar.add(AddMenu);

        EditMenu.setText("Edit");

        EditTrainingMenuItem.setText("Training");
        EditTrainingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTrainingMenuItemActionPerformed(evt);
            }
        });
        EditMenu.add(EditTrainingMenuItem);

        EditStudentMenuItem.setText("Student");
        EditStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStudentMenuItemActionPerformed(evt);
            }
        });
        EditMenu.add(EditStudentMenuItem);

        AdministratorMenuBar.add(EditMenu);

        SearchMenu.setText("Search");

        SearchLocationMenuItem.setForeground(new java.awt.Color(102, 102, 0));
        SearchLocationMenuItem.setText("Location");
        SearchLocationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchLocationMenuItemActionPerformed(evt);
            }
        });
        SearchMenu.add(SearchLocationMenuItem);

        SearchSessionMenuItem.setForeground(new java.awt.Color(102, 102, 0));
        SearchSessionMenuItem.setText("Session");
        SearchSessionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSessionMenuItemActionPerformed(evt);
            }
        });
        SearchMenu.add(SearchSessionMenuItem);

        SearchStudentMenuItem.setForeground(new java.awt.Color(102, 102, 0));
        SearchStudentMenuItem.setText("Student");
        SearchStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchStudentMenuItemActionPerformed(evt);
            }
        });
        SearchMenu.add(SearchStudentMenuItem);

        SearchTrainingMenuItem.setForeground(new java.awt.Color(102, 102, 0));
        SearchTrainingMenuItem.setText("Training");
        SearchTrainingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTrainingMenuItemActionPerformed(evt);
            }
        });
        SearchMenu.add(SearchTrainingMenuItem);

        AdministratorMenuBar.add(SearchMenu);

        ReportsMenu.setText("Reports");

        jMenu4.setText("Sessions");

        SessionsStudentsInformationMenuItem.setText("Students Information");
        SessionsStudentsInformationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionsStudentsInformationMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(SessionsStudentsInformationMenuItem);

        SessionsDurationMenuItem.setText("Duration");
        SessionsDurationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionsDurationMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(SessionsDurationMenuItem);

        ReportsMenu.add(jMenu4);

        StudentsInformationMenuItem.setText("Students Informations");
        StudentsInformationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsInformationMenuItemActionPerformed(evt);
            }
        });
        ReportsMenu.add(StudentsInformationMenuItem);

        AdministratorMenuBar.add(ReportsMenu);

        OptionsMenu.setText("Options");

        ChangePasswordMenuItem.setText("Change User Password");
        ChangePasswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordMenuItemActionPerformed(evt);
            }
        });
        OptionsMenu.add(ChangePasswordMenuItem);

        AdministratorMenuBar.add(OptionsMenu);

        setJMenuBar(AdministratorMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddSessionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSessionMenuItemActionPerformed
        
        asef.setVisible(true);
        asef.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        asef.setLocationRelativeTo(null);
        asef.setResizable(false);
    }//GEN-LAST:event_AddSessionMenuItemActionPerformed

    private void ChangePasswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordMenuItemActionPerformed

        ctrpf.setVisible(true);
        ctrpf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ctrpf.setLocationRelativeTo(null);
        ctrpf.setResizable(false);
    }//GEN-LAST:event_ChangePasswordMenuItemActionPerformed

    private void AddTrainingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTrainingMenuItemActionPerformed
        atf.setVisible(true);
        atf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        atf.setLocationRelativeTo(null);
        atf.setResizable(false);
    }//GEN-LAST:event_AddTrainingMenuItemActionPerformed

    private void AddStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentMenuItemActionPerformed
        asf.setVisible(true);
        asf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        asf.setLocationRelativeTo(null);
        asf.setResizable(false);
    }//GEN-LAST:event_AddStudentMenuItemActionPerformed

    private void EditTrainingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTrainingMenuItemActionPerformed
        stf.setVisible(true);
        stf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        stf.setLocationRelativeTo(null);
        stf.setResizable(false);
    }//GEN-LAST:event_EditTrainingMenuItemActionPerformed

    private void EditStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStudentMenuItemActionPerformed
        ssf.setVisible(true);
        ssf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ssf.setLocationRelativeTo(null);
        ssf.setResizable(false);
    }//GEN-LAST:event_EditStudentMenuItemActionPerformed

    private void SessionsStudentsInformationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionsStudentsInformationMenuItemActionPerformed
        try{
            ods=new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("alnayzak");
            ods.setPassword("123456");
            con=ods.getConnection();
            input=new FileInputStream(new File("C:\\Reports\\SessionStudent.jrxml"));
            jasperDesign=JRXmlLoader.load(input);
            jasperReport=JasperCompileManager.compileReport(jasperDesign);
            jasperPrint=JasperFillManager.fillReport(jasperReport, null, con);

            JFrame frame = new JFrame("Sessions Students Informations");
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.pack();
            frame.setVisible(true);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_SessionsStudentsInformationMenuItemActionPerformed

    private void SessionsDurationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionsDurationMenuItemActionPerformed
        try{
            ods=new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("alnayzak");
            ods.setPassword("123456");
            con=ods.getConnection();
            input=new FileInputStream(new File("C:\\Reports\\SessionsDuration.jrxml"));
            jasperDesign=JRXmlLoader.load(input);
            jasperReport=JasperCompileManager.compileReport(jasperDesign);
            jasperPrint=JasperFillManager.fillReport(jasperReport, null, con);

            JFrame frame = new JFrame("Sessions Duration Informations");
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.pack();
            frame.setVisible(true);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_SessionsDurationMenuItemActionPerformed

    private void StudentsInformationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsInformationMenuItemActionPerformed
        try{
            ods=new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("alnayzak");
            ods.setPassword("123456");
            con=ods.getConnection();
            input=new FileInputStream(new File("C:\\Reports\\Student.jrxml"));
            jasperDesign=JRXmlLoader.load(input);
            jasperReport=JasperCompileManager.compileReport(jasperDesign);
            jasperPrint=JasperFillManager.fillReport(jasperReport, null, con);

            JFrame frame = new JFrame("All Students Informations");
            frame.getContentPane().add(new JRViewer(jasperPrint));
            frame.pack();
            frame.setVisible(true);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_StudentsInformationMenuItemActionPerformed

    private void SearchLocationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchLocationMenuItemActionPerformed
        Sslf.setVisible(true);
        Sslf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Sslf.setLocationRelativeTo(null);
        Sslf.setResizable(false);
    }//GEN-LAST:event_SearchLocationMenuItemActionPerformed

    private void SearchSessionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSessionMenuItemActionPerformed
        Sssef.setVisible(true);
        Sssef.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Sssef.setLocationRelativeTo(null);
        Sssef.setResizable(false);
    }//GEN-LAST:event_SearchSessionMenuItemActionPerformed

    private void SearchStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchStudentMenuItemActionPerformed
        Sssf.setVisible(true);
        Sssf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Sssf.setLocationRelativeTo(null);
        Sssf.setResizable(false);
    }//GEN-LAST:event_SearchStudentMenuItemActionPerformed

    private void SearchTrainingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTrainingMenuItemActionPerformed
        Sstf.setVisible(true);
        Sstf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Sstf.setLocationRelativeTo(null);
        Sstf.setResizable(false);
    }//GEN-LAST:event_SearchTrainingMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AddMenu;
    private javax.swing.JMenuItem AddSessionMenuItem;
    private javax.swing.JMenuItem AddStudentMenuItem;
    private javax.swing.JMenuItem AddTrainingMenuItem;
    private javax.swing.JMenuBar AdministratorMenuBar;
    private javax.swing.JMenuItem ChangePasswordMenuItem;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem EditStudentMenuItem;
    private javax.swing.JMenuItem EditTrainingMenuItem;
    private javax.swing.JMenu OptionsMenu;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JMenuItem SearchLocationMenuItem;
    private javax.swing.JMenu SearchMenu;
    private javax.swing.JMenuItem SearchSessionMenuItem;
    private javax.swing.JMenuItem SearchStudentMenuItem;
    private javax.swing.JMenuItem SearchTrainingMenuItem;
    private javax.swing.JMenuItem SessionsDurationMenuItem;
    private javax.swing.JMenuItem SessionsStudentsInformationMenuItem;
    private javax.swing.JMenuItem StudentsInformationMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
